services:
#  inference:
#  add inference service using
  backend:
    build:
      context: services/backend/
      target: final
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - PG_DBNAME=${PG_DBNAME}
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - RUST_LOG=${RUST_LOG}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_DBNAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
