name: Pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
